### ISSUE TITLE
버전에 대한 issue

### ISSUE THREAD

**Issue by 1000peach** [LeeEunhyung/OSS_2048#15]
지금까지의 tag로 달았던 version의 규칙을 바꾸는 게 좋을 것 같다는 의견이 나왔습니다!

`v_._._ _`
위처럼 기존 버전 규칙은 z 자리를 두 개로 나눠서 카운트 했습니다.
하지만 이 규칙은 개선 내용이 많아지면 카운트되는 버전 넘버를 다 담을 수 없어 다른 방식의 tag 규칙을 정해야 할 것 같습니다!

새로운 규칙에 대한 의견은 코멘트로 달아주세요!

**Comment by LeeEunhyung** [comment]
z 자리를 두 개로 나눠서 각각 카운트 하면 
개선 사항을 확인할 수 있기는 하지만 해당 개선 사항을 0부터 9까지밖에 카운트하지 못해서 제약이 있는 것같아요!
두 개로 나눈걸 같이 카운트하고 개선 사항에 대해서 팀원들에게 알려주는 방식은 어떨까요?!

`v_._._`
위의 형식으로 합치고 z자리가 포함하는 개선 사항은 코드 개선이랑 버그 수정 시에 같이 올라가는거에요!!

**Comment by 1000peach** [comment]
좋아요! 
그러면 지금까지의 pull request에 대해서 변경된 버전을 코멘트로 다시 달까요?
팀원들에게 바뀐 버전을 알리는 용도로요!

**Comment by 1000peach** [comment]
> z 자리를 두 개로 나눠서 각각 카운트 하면
> 개선 사항을 확인할 수 있기는 하지만 해당 개선 사항을 0부터 9까지밖에 카운트하지 못해서 제약이 있는 것같아요!
> 두 개로 나눈걸 같이 카운트하고 개선 사항에 대해서 팀원들에게 알려주는 방식은 어떨까요?!
> 
> `v_._._`
> 위의 형식으로 합치고 z자리가 포함하는 개선 사항은 코드 개선이랑 기능 개선, 버그 수정 시에 같이 올라가는거에요!!

좋아요!
그러면 지금까지의 pull request에 대해서 변경된 버전을 코멘트로 다시 달까요?
팀원들에게 바뀐 버전을 알리는 용도로요!

**Comment by wlals7217** [comment]
좋습니다! 버전에 혼선이 있어서 곤란했어요. 처음부터 확실히 정했으면 좋았겠네요.

**Comment by wlals7217** [comment]
그것도 확실히 정하면 좋을 것 같아요 앞 자리 버전 넘버가 올라가면 뒷 자리는 초기화되는걸로 정하면 좋겠어요! 예를 들어 v.0.1.12에서 두 번째 버전 넘버가 올라가면 v0.2.0으로 뒷 자리는 초기화 되도록 하는게 좋겠어요!

**Comment by LeeEunhyung** [comment]
위의 규칙 정리 사항입니다!

- x 자리: 완성 시
- y 자리: 기능 개선 시
- z 자리: 코드 수정, 버그 수정
- branch마다 1씩 증가
- 앞 자리 증가 시. 뒷 자리 초기화

**Comment by 1000peach** [comment]
> 위의 규칙 정리 사항입니다!
> 
> * x 자리: 완성 시
> * y 자리: 기능 개선 시
> * z 자리: 코드 수정, 버그 수정
> * branch마다 1씩 증가
> * 앞 자리 증가 시. 뒷 자리 초기화

정리 감사합니다. 지금까지 close 된 pull request에 각자 comment로 바뀐 version 을 달기로 해요!

- 이전 버전이 명시된 pull request: v0.0.21 -> v0.1.0 Environment improvement version
- 이전 버전이 명시되지 않은 pull request: v0.1.0 Environment improvement version

**Comment by 1000peach** [comment]
issue에 대한 토론이 끝났으니 닫겠습니다!
