### ISSUE TITLE
commit 시간과 관련된 issue와 공지

### ISSUE THREAD

**Issue by 1000peach** [LeeEunhyung/OSS_2048#21]
저는 협업을 위해 가상머신을 쓰고 있는데, 리눅스 우분투에서는 현재 시간이 맞지 않았습니다.
그래서 터미널 창에서 명령어 또는 GUI 설정 창에서 시간과 날짜를 맞게 다시 설정했습니다.
그럼에도 불구하고 git log 에서는 변경하여 올바른 시간으로 기록이 되지만 github 기록에서는 commit 시간이 현재와 다르게 표시 되는 걸 발견 하였습니다.

이 같은 문제점은 해당 부분에 대해 git log로 봐주시면 될 것 같아요!
pull request에 답글로 달았지만, 눈에 띄지 않아 issue로 남깁니다.
혼란을 야기해서 죄송합니다..!

@LeeEunhyung @wlals7217 #

**Comment by wlals7217** [comment]
혼란스러운건 교수님 만 그러실 것 같네요! 저는 상관 없습니다! 확인했어요!

**Comment by LeeEunhyung** [comment]
알겠습니다!! git log 기록은 오류가 안나서 다행이에요!~!

**Comment by 1000peach** [comment]
이해해주셔서 감사합니다. 해당 Issue는 닫겠습니다! 👍
