### ISSUE TITLE
마지막 수정 작업을 위한 branch에 대한 issue

### ISSUE THREAD

**Issue by LeeEunhyung** [LeeEunhyung/OSS_2048#24]
**마지막 수정 작업을 위한 branch에 대한 issue**

이제 전반적인 코드 개선은 완료했습니다!
문서 관련 작업은 진행 중에 있습니다.

마지막으로 세세하게 코드를 리뷰해보시고 
발견된 오타나 변수, 함수 이름 변경, 괄호 위치, 주석 등 교안을 참고해서 추가적으로 수정이 필요한 부분들을 comment로 달아주세요!
마지막 branch의 이름은 release_1으로 하려고 하는데 의견 있으신 분들은 알려주세요!
comment 하나씩 고쳐서 작은 commit으로 수정 후 pull request하겠습니다!!
이제 얼마 안남았습니다! 화이팅 👍 
@1000peach  @wlals7217

**Comment by LeeEunhyung** [comment]
- r, x, e키 대문자도 설정하도록 하기

**Comment by LeeEunhyung** [comment]
- isGameOver()의 리턴값을 변수에 저장해 조건문에 넣기

**Comment by 1000peach** [comment]
branch 이름 동의합니다!
그리고 코드를 보면, gameboard의 한 칸을 tile로 정의할 때도 있고 block으로 정의할 때도 있는데 하나로 통일 됐으면 좋겠습니다.

**Comment by 1000peach** [comment]
그리고 주석의 포맷도 명령문이나 평서문 둘 중 하나로 끝나는데, 이것도 명령문으로 통일 했으면 좋겠어요!
다들 좀 더 힘냅시다!

**Comment by LeeEunhyung** [comment]
넵!! 이 issue는 5월 30일 8:30 PM에 Close하겠습니다!

**Comment by LeeEunhyung** [comment]
- 추가된 변수 주석 달기

**Comment by LeeEunhyung** [comment]
- 변수 선언 시, 같은 성격을 가지는 변수를 동일한 라인에 배치

**Comment by wlals7217** [comment]
메인 
- 60번째 줄 	emptyIndex = (int *)malloc(sizeof(int)*(size*size));
곱셈연산자 띄어썼으면 좋겠습니다. 
- 79 번째 줄 isMoved = 0; 
0대신 FALSE로 바꿨으면 좋겠습니다. (클릭변수도 가능하면)
- 변수명 형태가 example_value, exampleValue 둘 로 나눠있는데  이유가 없다면 통일하는게 좋을 것 같습니다.
- spawnBlock 함수가 게임보드 사이즈가 10이 넘어가면 작동을 안합니다. #define MAX_BOARD_SIZE 1000정도? 하고 // 10의 제곱수 추천
void spawnBlock(int **cur_board, int *emptyIndex, int size) {

	int emptyTile = 0;
	int randomIndex = 0;
	int randomNum = 0;
	int i = 0;
	int j = 0;

	for (i = 0; i <= size - 1; i++) {
		for (j = 0; j <= size; j++) {
			if (cur_board[i][j] == 0) {
				emptyIndex[emptyTile] = MAX_BOARD_SIZE * i + j;
				emptyTile = emptyTile + 1;
			}
		}
	}
	randomIndex = rand() % emptyTile;
	i = emptyIndex[randomIndex] / MAX_BOARD_SIZE;
	j = emptyIndex[randomIndex] % MAX_BOARD_SIZE;
	randomNum = ((rand() % 2) + 1) * 2;
	cur_board[i][j] = randomNum;
}//게임보드에서 빈자리를 검색해 배열에 x*MAX_BOARD_SIZE + y로 인덱싱하고 랜덤으로 뽑아서 2 또는 4 블록을 배치한다.
요렇게 고쳐야 될 것 같은데 제가할까요??

- 다음과 같이 되어 있는 for문이 많은데 
			for (j = 0; j <= size - 1; j++) {
				for (i = size - 1; i > 0; i--) {
i가 먼저 올라가면 메모리 효율이 떨어져서
for (i = size - 1; i > 0; i--) {
for (j = 0; j <= size - 1; j++) {
위와 같이 순서를 바꿔주면 좋을 것 같습니다.

**Comment by LeeEunhyung** [comment]
넵 알겠습니다!

**Comment by LeeEunhyung** [comment]
- 전역 변수로 선언된 key 값을 매개변수로 받는 부분 수정하기

**Comment by LeeEunhyung** [comment]
- InitGame.h에서 define된 SECOND_ARROW값 Linux에서만 정의하기

**Comment by LeeEunhyung** [comment]
- return 값 0과 1인 경우에 define된 TRUE/FALSE로 설정하기

**Comment by LeeEunhyung** [comment]
- 사용하지 않는 함수 지우기

**Comment by LeeEunhyung** [comment]
***생각보다 수정해야할 내용이 많아서 fix, clean, improve로 나눠서 commit하겠습니다***

**Comment by LeeEunhyung** [comment]
close하겠습니다!
